# Trading Configuration
trading:
  min_signal_ratio: 1.25
  min_confidence_threshold: 0.3
  max_positions: 5
  position_timeout_minutes: 10
  
# Superp Configuration  
superp:
  min_buy_in: 10.0
  max_buy_in: 100.0
  max_leverage: 10000.0
  
# ML Engine Settings
ml:
  scan_interval_seconds: 45
  prediction_history_limit: 1000
  model_retrain_interval_hours: 24
  confidence_threshold: 0.3
  min_return_threshold: 0.001  # 0.1%
  
# TradingView Integration
tradingview:
  timeframes: ["1m", "5m", "10m"]
  analysis_interval_seconds: 30
  confirmation_threshold: 0.4
  
# Risk Management
risk:
  max_total_exposure: 1000.0
  max_positions_per_asset: 2
  emergency_stop_loss_percent: 0.95
  
# Monitoring
monitoring:
  health_check_interval_seconds: 60
  log_level: "INFO"
  enable_performance_tracking: true
  
# Telegram Configuration
telegram_token: "example"
telegram_chat_id: "example"

# Notifications
notifications:
  telegram_enabled: true
  high_confidence_only: false
  timer_alerts: false
  timer_notifications: false
